from functions.run_python_file import *

print("Run calculator")
print(run_python_file("calculator", "main.py"))
print("-----------------------------")
print("Run calculator with sum")
print(run_python_file("calculator", "main.py", ["3 + 5"]))
print("-----------------------------")
print("Run calculator tests")
print(run_python_file("calculator", "tests.py"))
print("-----------------------------")
print("Run outside working directory")
print(run_python_file("calculator", "../main.py"))
print("-----------------------------")
print("Run missing file")
print(run_python_file("calculator", "nonexistent.py"))
print("-----------------------------")
print("Run invalid file")
print(run_python_file("calculator", "lorem.txt"))
print("-----------------------------")